UT's register in git workflows

diff --git a/.github/workflows/basyx_test.yml b/.github/workflows/basyx_test.yml
--- a/.github/workflows/basyx_test.yml
+++ b/.github/workflows/basyx_test.yml
@@ -736,6 +736,67 @@ jobs:
             exit 1;
           fi
 
+  test-basyx-aasdigitaltwinregistry:
+    runs-on: ubuntu-latest
+    name: AAS Digital Twin Registry Service Test
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'adopt'
+          cache: maven
+
+
+      - name: Build BaSyx
+        run: mvn clean install ${MVN_ARGS_BUILD_BASYX}
+
+      - name: Build Discovery Service
+        run: mvn package -DskipTests -Ddocker.namespace=eclipsebasyx --pl "org.eclipse.digitaltwin.basyx:basyx.aasdiscoveryservice.component"
+
+      - name: Build Submodel Repository
+        run: mvn package -DskipTests -Ddocker.namespace=eclipsebasyx --pl "org.eclipse.digitaltwin.basyx:basyx.submodelrepository.component"
+
+      - name: Build AAS Repository
+        run: mvn package -DskipTests -Ddocker.namespace=eclipsebasyx --pl "org.eclipse.digitaltwin.basyx:basyx.aasrepository.component"
+
+      - name: Build AAS Registry Log Mem
+        run: mvn package -DskipTests -Ddocker.namespace=eclipsebasyx --pl "org.eclipse.digitaltwin.basyx:basyx.aasregistry-service-release-log-mem"
+
+      - name: Build Submodel Registry Log Mem
+        run: mvn package -DskipTests -Ddocker.namespace=eclipsebasyx --pl "org.eclipse.digitaltwin.basyx:basyx.submodelregistry-service-release-log-mem"
+
+      - name: Build AAS Registry Log MongoDB
+        run: mvn package -DskipTests -Ddocker.namespace=eclipsebasyx --pl "org.eclipse.digitaltwin.basyx:basyx.aasregistry-service-release-log-mongodb"
+
+      - name: Build Submodel Registry Log MongoDB
+        run: mvn package -DskipTests -Ddocker.namespace=eclipsebasyx --pl "org.eclipse.digitaltwin.basyx:basyx.submodelregistry-service-release-log-mongodb"
+
+      - name: Start environment
+        run: docker compose --project-directory ./ci up -d --wait
+
+      - name: Test BaSyx Common
+        run: mvn test -f "basyx.common/pom.xml"
+
+      - name: Test AAS Digital Twin Registry Service
+        run: mvn test -f "basyx.aasdigitaltwinregistry/pom.xml" -DskipITs
+
+      - name: Fail if no Surefire/Failsafe reports found
+        run: |
+          if ! find . -type f \( -path "*/target/surefire-reports/*.xml" -o -path "*/target/failsafe-reports/*.xml" \) | grep -q .; then
+            echo "No Surefire or Failsafe test reports found. Failing CI.";
+            exit 1;
+          fi
+
+      - name: Fail if no Surefire/Failsafe reports found
+        run: |
+          if ! find . -type f \( -path "*/target/surefire-reports/*.xml" -o -path "*/target/failsafe-reports/*.xml" \) | grep -q .; then
+            echo "No Surefire or Failsafe test reports found. Failing CI.";
+            exit 1;
+          fi
+
       - name: Stop environment
         if: always()
         run: docker compose --project-directory ./ci down
