Changes workflow

diff --git a/.github/workflows/maven_run_test.yml b/.github/workflows/maven_run_test.yml
--- a/.github/workflows/maven_run_test.yml
+++ b/.github/workflows/maven_run_test.yml
@@ -41,7 +41,51 @@ jobs:
       - name: Stop environment
         if: always()
         run: docker compose --project-directory ./ci down
-  Build-Docker-Images:
+  Build-AAS-CD-Docker-Images:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'adopt'
+          cache: maven
+      - name: Build Docker Images
+        run: |
+          mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.aasrepository.component"
+          mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.aasenvironment.component"
+          mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.conceptdescriptionrepository.component"
+          mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.aasdiscoveryservice.component"
+          mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.aasxfileserver.component"
+
+      - name: Test Docker Images
+        run: |
+          images=("basyx.aasrepository.component" "basyx.aasenvironment.component" "basyx.conceptdescriptionrepository.component" "basyx.aasdiscoveryservice.component" "basyx.aasxfileserver.component")
+          
+          for image in "${images[@]}"; do
+            echo "Testing image $image"
+            docker run -d --name test_$image test/$image
+            sleep 30  # Give the container some time to start
+
+            # Check if the container is healthy (assuming the Dockerfile defines a HEALTHCHECK)
+            if [ "$(docker inspect --format='{{.State.Health.Status}}' test_$image)" == "healthy" ]; then
+              echo "$image started successfully and is healthy."
+            else
+              echo "$image failed to start or is unhealthy."
+              docker logs test_$image
+              exit 1
+            fi
+
+            # Stop and remove the container after testing
+            docker stop test_$image
+            docker rm test_$image
+          done
+
+      - name: Clean up Docker Images
+        run: |
+          docker rmi -f $(docker images -aq)
+  Build-Submodel-Docker-Images:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -55,15 +99,88 @@ jobs:
         run: |
           mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.submodelservice.example"
           mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.submodelrepository.component"
-          mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.aasrepository.component"
-          mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.aasenvironment.component"
-          mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.conceptdescriptionrepository.component"
-          mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.aasdiscoveryservice.component"
-          mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.aasxfileserver.component"
+
+      - name: Test Docker Images
+        run: |
+          images=("basyx.submodelservice.example" "basyx.submodelrepository.component")
+          
+          for image in "${images[@]}"; do
+            echo "Testing image $image"
+            docker run -d --name test_$image test/$image
+            sleep 30  # Give the container some time to start
+
+            # Check if the container is healthy (assuming the Dockerfile defines a HEALTHCHECK)
+            if [ "$(docker inspect --format='{{.State.Health.Status}}' test_$image)" == "healthy" ]; then
+              echo "$image started successfully and is healthy."
+            else
+              echo "$image failed to start or is unhealthy."
+              docker logs test_$image
+              exit 1
+            fi
+
+            # Stop and remove the container after testing
+            docker stop test_$image
+            docker rm test_$image
+          done
+
+      - name: Clean up Docker Images
+        run: |
+          docker rmi -f $(docker images -aq)
+  Build-AAS-Registry-Docker-Images:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'adopt'
+          cache: maven
+      - name: Build Docker Images
+        run: |
           mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.aasregistry-service-release-kafka-mem"
           mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.aasregistry-service-release-kafka-mongodb"
           mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.aasregistry-service-release-log-mem"
           mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.aasregistry-service-release-log-mongodb"
+
+      - name: Test Docker Images
+        run: |
+          images=("basyx.aasregistry-service-release-kafka-mem" "basyx.aasregistry-service-release-kafka-mongodb" "basyx.aasregistry-service-release-log-mem" "basyx.aasregistry-service-release-log-mongodb")
+          
+          for image in "${images[@]}"; do
+            echo "Testing image $image"
+            docker run -d --name test_$image test/$image
+            sleep 30  # Give the container some time to start
+
+            # Check if the container is healthy (assuming the Dockerfile defines a HEALTHCHECK)
+            if [ "$(docker inspect --format='{{.State.Health.Status}}' test_$image)" == "healthy" ]; then
+              echo "$image started successfully and is healthy."
+            else
+              echo "$image failed to start or is unhealthy."
+              docker logs test_$image
+              exit 1
+            fi
+
+            # Stop and remove the container after testing
+            docker stop test_$image
+            docker rm test_$image
+          done
+
+      - name: Clean up Docker Images
+        run: |
+          docker rmi -f $(docker images -aq)
+  Build-Submodel-Registry-Docker-Images:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'adopt'
+          cache: maven
+      - name: Build Docker Images
+        run: |
           mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.submodelregistry-service-release-kafka-mem"
           mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.submodelregistry-service-release-kafka-mongodb"
           mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.submodelregistry-service-release-log-mem"
@@ -71,7 +188,7 @@ jobs:
 
       - name: Test Docker Images
         run: |
-          images=("basyx.submodelservice.example" "basyx.submodelrepository.component" "basyx.aasrepository.component" "basyx.aasenvironment.component" "basyx.conceptdescriptionrepository.component" "basyx.aasdiscoveryservice.component" "basyx.aasxfileserver.component" "basyx.aasregistry-service-release-kafka-mem" "basyx.aasregistry-service-release-kafka-mongodb" "basyx.aasregistry-service-release-log-mem" "basyx.aasregistry-service-release-log-mongodb" "basyx.submodelregistry-service-release-kafka-mem" "basyx.submodelregistry-service-release-kafka-mongodb" "basyx.submodelregistry-service-release-log-mem" "basyx.submodelregistry-service-release-log-mongodb")
+          images=("basyx.submodelregistry-service-release-kafka-mem" "basyx.submodelregistry-service-release-kafka-mongodb" "basyx.submodelregistry-service-release-log-mem" "basyx.submodelregistry-service-release-log-mongodb")
           
           for image in "${images[@]}"; do
             echo "Testing image $image"
