Changes workflow

diff --git a/.github/workflows/maven_run_test.yml b/.github/workflows/maven_run_test.yml
--- a/.github/workflows/maven_run_test.yml
+++ b/.github/workflows/maven_run_test.yml
@@ -41,7 +41,20 @@ jobs:
 
       - name: Build with Maven
         run: mvn package -DskipTests -T1C
+      - name: Check if previous workflows were successful
+        id: check_success
+        run: |
+          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "One or more of the required workflows failed."
+            echo "::set-output name=success::false"
+            exit 1
+          fi
+          echo "::set-output name=success::true"
+          
   build-test-aas-repository:
+    needs: check_previous_success
+    if: needs.check_previous_success.outputs.success == 'true'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -88,11 +101,20 @@ jobs:
           # Stop and remove the container after testing
           docker stop test_aas_repository
           docker rm test_aas_repository
-
-      - name: Clean up
-        run: exit 0
+      - name: Check if previous workflows were successful
+        id: check_success
+        run: |
+          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "One or more of the required workflows failed."
+            echo "::set-output name=success::false"
+            exit 1
+          fi
+          echo "::set-output name=success::true"
 
   build-test-aas-environment:
+    needs: check_previous_success
+    if: needs.check_previous_success.outputs.success == 'true'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -139,11 +161,20 @@ jobs:
           # Stop and remove the container after testing
           docker stop test_aas_environment
           docker rm test_aas_environment
-
-      - name: Clean up
-        run: exit 0
+      - name: Check if previous workflows were successful
+        id: check_success
+        run: |
+          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "One or more of the required workflows failed."
+            echo "::set-output name=success::false"
+            exit 1
+          fi
+          echo "::set-output name=success::true"
 
   build-test-concept-description-repository:
+    needs: check_previous_success
+    if: needs.check_previous_success.outputs.success == 'true'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -190,11 +221,20 @@ jobs:
           # Stop and remove the container after testing
           docker stop test_conceptdescription_repository
           docker rm test_conceptdescription_repository
-
-      - name: Clean up
-        run: exit 0
+      - name: Check if previous workflows were successful
+        id: check_success
+        run: |
+          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "One or more of the required workflows failed."
+            echo "::set-output name=success::false"
+            exit 1
+          fi
+          echo "::set-output name=success::true"
 
   build-test-aas-discovery:
+    needs: check_previous_success
+    if: needs.check_previous_success.outputs.success == 'true'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -241,11 +281,20 @@ jobs:
           # Stop and remove the container after testing
           docker stop test_aas_discovery
           docker rm test_aas_discovery
-
-      - name: Clean up
-        run: exit 0
+      - name: Check if previous workflows were successful
+        id: check_success
+        run: |
+          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "One or more of the required workflows failed."
+            echo "::set-output name=success::false"
+            exit 1
+          fi
+          echo "::set-output name=success::true"
 
   build-test-aasx-fileserver:
+    needs: check_previous_success
+    if: needs.check_previous_success.outputs.success == 'true'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -292,11 +341,20 @@ jobs:
           # Stop and remove the container after testing
           docker stop test_aasxfileserver
           docker rm test_aasxfileserver
-
-      - name: Clean up
-        run: exit 0
+      - name: Check if previous workflows were successful
+        id: check_success
+        run: |
+          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "One or more of the required workflows failed."
+            echo "::set-output name=success::false"
+            exit 1
+          fi
+          echo "::set-output name=success::true"
 
   build-test-submodel-repository:
+    needs: check_previous_success
+    if: needs.check_previous_success.outputs.success == 'true'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -343,11 +401,20 @@ jobs:
           # Stop and remove the container after testing
           docker stop test_submodel_repository
           docker rm test_submodel_repository
-
-      - name: Clean up
-        run: exit 0
+      - name: Check if previous workflows were successful
+        id: check_success
+        run: |
+          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "One or more of the required workflows failed."
+            echo "::set-output name=success::false"
+            exit 1
+          fi
+          echo "::set-output name=success::true"
 
   build-test-submodel-service:
+    needs: check_previous_success
+    if: needs.check_previous_success.outputs.success == 'true'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -394,11 +461,20 @@ jobs:
           # Stop and remove the container after testing
           docker stop test_submodel_service
           docker rm test_submodel_service
-
-      - name: Clean up
-        run: exit 0
+      - name: Check if previous workflows were successful
+        id: check_success
+        run: |
+          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "One or more of the required workflows failed."
+            echo "::set-output name=success::false"
+            exit 1
+          fi
+          echo "::set-output name=success::true"
 
   build-test-aas-registry-kafka-mem:
+    needs: check_previous_success
+    if: needs.check_previous_success.outputs.success == 'true'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -445,11 +521,20 @@ jobs:
           # Stop and remove the container after testing
           docker stop test_aas_registry_kafka_mem
           docker rm test_aas_registry_kafka_mem
-
-      - name: Clean up
-        run: exit 0
+      - name: Check if previous workflows were successful
+        id: check_success
+        run: |
+          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "One or more of the required workflows failed."
+            echo "::set-output name=success::false"
+            exit 1
+          fi
+          echo "::set-output name=success::true"
 
   build-test-aas-registry-kafka-mongodb:
+    needs: check_previous_success
+    if: needs.check_previous_success.outputs.success == 'true'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -496,11 +581,20 @@ jobs:
           # Stop and remove the container after testing
           docker stop test_aas_registry_kafka_mongodb
           docker rm test_aas_registry_kafka_mongodb
-
-      - name: Clean up
-        run: exit 0
+      - name: Check if previous workflows were successful
+        id: check_success
+        run: |
+          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "One or more of the required workflows failed."
+            echo "::set-output name=success::false"
+            exit 1
+          fi
+          echo "::set-output name=success::true"
 
   build-test-aas-registry-log-mem:
+    needs: check_previous_success
+    if: needs.check_previous_success.outputs.success == 'true'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -547,11 +641,20 @@ jobs:
           # Stop and remove the container after testing
           docker stop test_aas_registry_log_mem
           docker rm test_aas_registry_log_mem
-
-      - name: Clean up
-        run: exit 0
+      - name: Check if previous workflows were successful
+        id: check_success
+        run: |
+          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "One or more of the required workflows failed."
+            echo "::set-output name=success::false"
+            exit 1
+          fi
+          echo "::set-output name=success::true"
 
   build-test-aas-registry-log-mongodb:
+    needs: check_previous_success
+    if: needs.check_previous_success.outputs.success == 'true'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -598,11 +701,20 @@ jobs:
           # Stop and remove the container after testing
           docker stop test_aas_registry_log_mongodb
           docker rm test_aas_registry_log_mongodb
-
-      - name: Clean up
-        run: exit 0
+      - name: Check if previous workflows were successful
+        id: check_success
+        run: |
+          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "One or more of the required workflows failed."
+            echo "::set-output name=success::false"
+            exit 1
+          fi
+          echo "::set-output name=success::true"
 
   build-test-submodel-registry-kafka-mem:
+    needs: check_previous_success
+    if: needs.check_previous_success.outputs.success == 'true'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -649,11 +761,20 @@ jobs:
           # Stop and remove the container after testing
           docker stop test_submodel_registry_kafka_mem
           docker rm test_submodel_registry_kafka_mem
-
-      - name: Clean up
-        run: exit 0
+      - name: Check if previous workflows were successful
+        id: check_success
+        run: |
+          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "One or more of the required workflows failed."
+            echo "::set-output name=success::false"
+            exit 1
+          fi
+          echo "::set-output name=success::true"
 
   build-test-submodel-registry-kafka-mongodb:
+    needs: check_previous_success
+    if: needs.check_previous_success.outputs.success == 'true'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -700,11 +821,20 @@ jobs:
           # Stop and remove the container after testing
           docker stop test_submodel_registry_kafka_mongodb
           docker rm test_submodel_registry_kafka_mongodb
-
-      - name: Clean up
-        run: exit 0
+      - name: Check if previous workflows were successful
+        id: check_success
+        run: |
+          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "One or more of the required workflows failed."
+            echo "::set-output name=success::false"
+            exit 1
+          fi
+          echo "::set-output name=success::true"
 
   build-test-submodel-registry-log-mem:
+    needs: check_previous_success
+    if: needs.check_previous_success.outputs.success == 'true'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -751,11 +881,20 @@ jobs:
           # Stop and remove the container after testing
           docker stop test_submodel_registry_log_mem
           docker rm test_submodel_registry_log_mem
-
-      - name: Clean up
-        run: exit 0
+      - name: Check if previous workflows were successful
+        id: check_success
+        run: |
+          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "One or more of the required workflows failed."
+            echo "::set-output name=success::false"
+            exit 1
+          fi
+          echo "::set-output name=success::true"
 
   build-test-submodel-registry-log-mongodb:
+    needs: check_previous_success
+    if: needs.check_previous_success.outputs.success == 'true'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -802,6 +941,13 @@ jobs:
           # Stop and remove the container after testing
           docker stop test_submodel_registry_log_mongodb
           docker rm test_submodel_registry_log_mongodb
-
-      - name: Clean up
-        run: exit 0
+      - name: Check if previous workflows were successful
+        id: check_success
+        run: |
+          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "One or more of the required workflows failed."
+            echo "::set-output name=success::false"
+            exit 1
+          fi
+          echo "::set-output name=success::true"
